<?php

declare(strict_types=1);

namespace Sashalenz\EbayApi\Enums;

/**
 * Package Type Enum
 *
 * Package types for shipping.
 */
enum PackageType: string
{
    case LETTER = 'LETTER';
    case BULKY_GOODS = 'BULKY_GOODS';
    case CARAVAN = 'CARAVAN';
    case CARS = 'CARS';
    case EUROPALLET = 'EUROPALLET';
    case EXPANDABLE_TOUGH_BAGS = 'EXPANDABLE_TOUGH_BAGS';
    case EXTRA_LARGE_PACK = 'EXTRA_LARGE_PACK';
    case FURNITURE = 'FURNITURE';
    case INDUSTRY_VEHICLES = 'INDUSTRY_VEHICLES';
    case LARGE_CANADA_POSTBOX = 'LARGE_CANADA_POSTBOX';
    case LARGE_CANADA_POST_BUBBLE_MAILER = 'LARGE_CANADA_POST_BUBBLE_MAILER';
    case LARGE_ENVELOPE = 'LARGE_ENVELOPE';
    case MAILING_BOX = 'MAILING_BOX';
    case MEDIUM_CANADA_POST_BOX = 'MEDIUM_CANADA_POST_BOX';
    case MEDIUM_CANADA_POST_BUBBLE_MAILER = 'MEDIUM_CANADA_POST_BUBBLE_MAILER';
    case MOTORBIKES = 'MOTORBIKES';
    case ONE_WAY_PALLET = 'ONE_WAY_PALLET';
    case PACKAGE_THICK_ENVELOPE = 'PACKAGE_THICK_ENVELOPE';
    case PADDED_BAGS = 'PADDED_BAGS';
    case PARCEL_OR_PADDED_ENVELOPE = 'PARCEL_OR_PADDED_ENVELOPE';
    case ROLL = 'ROLL';
    case SMALL_CANADA_POST_BOX = 'SMALL_CANADA_POST_BOX';
    case SMALL_CANADA_POST_BUBBLE_MAILER = 'SMALL_CANADA_POST_BUBBLE_MAILER';
    case TOUGH_BAGS = 'TOUGH_BAGS';
    case UPS_LETTER = 'UPS_LETTER';
    case USPS_FLAT_RATE_ENVELOPE = 'USPS_FLAT_RATE_ENVELOPE';
    case USPS_LARGE_PACK = 'USPS_LARGE_PACK';
    case VERY_LARGE_PACK = 'VERY_LARGE_PACK';
    case WINE_PAK = 'WINE_PAK';
}
